packageExtensions:
    '@anteris/parcel-transformer-html-literals@*':
        peerDependencies:
            '@parcel/core': '*'
    '@firebase/analytics@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/app-check@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/auth-types@*':
        dependencies:
            '@firebase/app-types': '*'
    '@firebase/auth@*':
        dependencies:
            '@firebase/app': '*'
            '@firebase/app-types': '*'
    '@firebase/firestore-types@*':
        dependencies:
            '@firebase/app-types': '*'
    '@firebase/firestore@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/functions@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/installations-types@*':
        dependencies:
            '@firebase/app-types': '*'
    '@firebase/installations@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/messaging@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/performance@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/remote-config@*':
        dependencies:
            '@firebase/app': '*'
    '@firebase/storage-types@*':
        dependencies:
            '@firebase/app-types': '*'
    '@firebase/storage@*':
        dependencies:
            '@firebase/app': '*'
    '@parcel/bundler-default@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/compressor-raw@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/namer-default@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/optimizer-css@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/optimizer-htmlnano@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/optimizer-image@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/optimizer-svgo@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/optimizer-terser@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/packager-css@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/packager-html@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/packager-js@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/packager-raw@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/packager-svg@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/plugin@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/reporter-cli@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/reporter-dev-server@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/resolver-default@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/resolver-glob@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/runtime-browser-hmr@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/runtime-js@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/runtime-react-refresh@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/runtime-service-worker@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-babel@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-css@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-html@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-json@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-postcss@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-posthtml@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-raw@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-react-refresh-wrap@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/transformer-svg@*':
        peerDependencies:
            '@parcel/core': '*'
    '@parcel/types@*':
        peerDependencies:
            '@parcel/core': '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
