name: Deploy to Firebase Functions and Database via github action
'on':
    push:
        branches:
            - deployed
        paths:
            - 'functions/**'
            - 'mamk-config.json'
            - 'rules.bolt'
env:
    CI: false
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Resolve dependencies
              run: yarn install && yarn run check
            - name: Deploy
              run: yarn run firebase deploy --only functions,database
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
