name: Deploy to Firebase Functions via github action
'on':
    push:
        branches:
            - deployed
env:
    CI: false
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Resolve dependencies and deploy
              working-directory: functions
              run: npm install
            - name: Deploy
              run: npx --yes firebase-tools deploy
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
