name: Deploy to Firebase Functions via github action
'on':
    push:
        branches:
            - main
        paths:
            - 'functions/**'
            - 'mamk-config.json'
env:
    CI: false
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Resolve dependencies and deploy
              working-directory: functions
              run: yarn set version latest && yarn && yarn add firebase-tools
            - name: Deploy
              run: yarn run firebase deploy --only functions,database -P dev
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_SECRET }}
